// src/app/components/timetable-cell/timetable-cell.component.ts
import { Component, Input } from '@angular/core';
import { ClassType } from '../../scripts/timetable';
import { convertInstructorCodeToInstructorName, convertSubjectCodeToSubjectName } from '../../scripts/translations';

@Component({
  selector: 'app-timetable-cell',
  imports: [],
  templateUrl: './timetable-cell.component.html',
  styleUrl: './timetable-cell.component.scss'
})
export class TimetableCellComponent {
  @Input() subject_code: string = '';
  @Input() location: string = '';
  @Input() instructor: string = '';
  @Input() double_size?: boolean;
  @Input() class_type: ClassType = 'lecture';

  convertInstructorCodeToInstructorName = convertInstructorCodeToInstructorName;
  convertSubjectCodeToSubjectName = convertSubjectCodeToSubjectName;
}

<div (class)="'subject ' + class_type">
    <div class="name">
      {{ convertSubjectCodeToSubjectName(subject_code) }}
    </div>
    <a (href)="'/map?target=' + location" class="location">
      {{ location }}
    </a>
    <div class="smol instructor">
      {{ convertInstructorCodeToInstructorName(instructor) }}
    </div>
  </div>

// apps/frontend/src/components/TimeTableCell.vue
<script setup lang="ts">
import { convertInstructorCodeToInstructorName, convertSubjectCodeToSubjectName } from '../scripts/translations';
import { Class } from './timetable_type';

const props = defineProps<{
  data: Class
}>();
</script>

<template>
  <div :class="'subject ' + data.class_type">
    <div class="name">
      {{ convertSubjectCodeToSubjectName(data.subject_code) }}
    </div>
    <a :href="'/map?target=' + data.location" class="location">
      {{ data.location }}
    </a>
    <div class="smol instructor">
      {{ convertInstructorCodeToInstructorName(data.instructor) }}
    </div>
  </div>
</template>

<style scoped>
.subject {
  background-color: var(--grey2);
  padding: 0.5rem;
  display: flex;
  flex-direction: column;
  justify-content: center;
  text-align: center;
  height: 6rem;
}
.lecture {
  background-color: var(--red);
  cursor: pointer;
}
.tutorial {
  background-color: var(--blue);
}
.lab {
  background-color: var(--green);
}
.smol {
  font-size: 0.8rem;
}
</style>
